name: Beta Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Beta Release
    if: ${{ github.repository_owner == 'james-elicx' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Set outputs
        id: hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Alter version
        run: npm run alter-version ${{ steps.hash.outputs.sha_short }} BETA

      - name: Build
        run: npm run build

      - name: Set publishing config
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: |
          cd dist
          npm publish --tag beta --no-git-checks
